Project HSX {
    database_type: 'PostgreSQL'
    Note: 'HSX'
}
// KO VIET HOA TEN BANG, TEN COLUMNS
// null, non-null
// primary key
// logic test date > ngay thanh lap ck 
// logic test case
Table delisted_tickers {        
    ticker_id varchar 
    isin varchar(12)
    figi varchar(12)
    company_name text [ unique, not null ]
    delist_date date
    volume bigint
    note: " "
}

Table new_listing_tickers {
    ticker varchar
    isin varchar (12)
    figi varchar (12)
    company_name text
    adress text
    submission_date date 
    regist_volume bigint
}

Table cw_list {
    issuer varchar
    cw_name varchar (255) [primary key]
    registration_vol integer
    conversion_ratio varchar
    submission_date date
    acceptedon date
    1sttrading_date date 
    maturity_date date
    note: "not relevant to others"
}
// Enum post_status {
// draft
// published
// private [note: 'visible via URL only']
// }

// ref for these tables in meaningless 